models:
  - name: EventReference
    mixins: [Trackable]
    columns:
      - name: rating
        type: integer
        default: 50
    relationships:
      - name: event
        target_model: Event
        pattern: many-to-one
        relation: parent
        back_populates: references
      - name: admin_unit
        target_model: AdminUnit
        pattern: many-to-one
        relation: parent
        back_populates: references
    constraints:
      - type: unique
        columns: [event_id, admin_unit_id]
